# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Kubeval - Kubernetes yaml validation
        uses: makocchi-git/actions-k8s-manifests-validate@v1.0.0
        if: ${{ always() }}
        with:
          files: /github/workspace/namespaces
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Kubeval - Kubernetes toolset
        uses: stefanprodan/kube-tools@v1.4.0
        if: ${{ always() }}
        with:
          command: |
            echo "Run kubeval"
            kubeval -d namespaces,workloads --strict --ignore-missing-schemas  


